      - name: Build APK
        run: |
          # Ek temporary config file banana taaki appId ka error na aaye
          echo '{"appId": "com.mejai.remindr", "appName": "Remindr", "webDir": "dist"}' > capacitor.config.json
          
          # Android platform setup
          npx cap add android || true
          npx cap sync
          
          # APK compile karna
          cd android && ./gradlew assembleDebug
          
          
          
